### ISSUE TITLE
Download link to installable for macOS missing in documentation

### ISSUE THREAD

**Issue by hlapp** [fairdataihub/FAIRshare#244]
**Describe the bug**
The "Download now" button on the website first tries to open in a popup (why?). Eventually it redirects to the same place as the "Explore the docs" button, the "Download FAIRshare" page. The "MacOS" section has a hyperlink labeled "Download the macOS installer", but it links to anchor "#macos" on the same page, not to (presumably) the installable as part of a Github release.

**To Reproduce**

1. Go to https://docs.fairshareapp.io/docs/getting-started/download-fairshare
2. Click on "Download FAIRshare"

**Expected behavior**
Should go to the installable, not the heading of the section.

**Comment by megasanjay** [comment]
Thank you for providing this feedback. At the moment, we use JS after you click on the link to create the download object but It does make more sense to be more upfront on the urls. 

I was able to update the links on our main website to better represent the data flow path. Our docs will also be updated soon to be more transparent regarding this process.

**Comment by megasanjay** [comment]
These links have now been updated and are live. Thank you for your feedback.
